//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jEntrancePosition
    {
        public int EntranceId { get; set; }
        public Nullable<int> IngridientId { get; set; }
        public Nullable<decimal> IngridientCost { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> EntranceDateTime { get; set; }
    
        public virtual hIngridient hIngridient { get; set; }
    }
}
