//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jMenuComposition
    {
        public int DishId { get; set; }
        public int DishAmount { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> DishDate { get; set; }
    
        public virtual hDishId hDishId { get; set; }
    }
}
